version: 1.0
services:
  l4d2:
    image: morzlee/l4d2
    ports:
    - "2333:2333"
    - "2333:2333/udp"
    - "27015:27015"
    - "27015:27015/udp"
    - "2334:2334"
    - "2334:2334/udp"
    - "2335:2335"
    - "2335:2335/udp"
    - "2336:2336"
    - "2336:2336/udp"
    environment:
      - HOSTNAME=leo
      - REGION=255
      - plugin=anne
      - steamid=STEAM_1:1:121430603
      - steamgroup=25622692,26419628
      - password=123456
      - index="first"
